name: fform_validator
description: fform_validator is a Flutter package that helps you to validate your form fields (optional).
version: 1.0.3
homepage: https://github.com/AlexHCJP/fform_validator
repository: https://github.com/AlexHCJP/fform_validator

environment:
  sdk: '>=2.12.0 <4.0.0'


  # Add regular dependencies here.
#dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.8
